//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS3
{
    using System;
    using System.Collections.Generic;
    
    public partial class billing
    {
        public int id { get; set; }
        public string invoiceDate { get; set; }
        public string invoiceDueDate { get; set; }
        public string amount { get; set; }
    }
}
